# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rlg_c1 <- function(x, d, alpha = 0.05, niter1 = 3L) {
    .Call(`_tclust_rlg_c1`, x, d, alpha, niter1)
}

rlg_c2 <- function(x, d, cluster, alpha = 0.05, niter2 = 20L) {
    .Call(`_tclust_rlg_c2`, x, d, cluster, alpha, niter2)
}

tclust_c1 <- function(x, k, alpha = 0.05, restrC = 0L, deterC = FALSE, restr_fact = 12, cshape = 1e10, niter1 = 3L, opt = "HARD", equal_weights = FALSE, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_c1`, x, k, alpha, restrC, deterC, restr_fact, cshape, niter1, opt, equal_weights, zero_tol)
}

tclust_c2 <- function(x, k, cluster, alpha = 0.05, restrC = 0L, deterC = FALSE, restr_fact = 12, cshape = 1e10, niter2 = 20L, opt = "HARD", equal_weights = FALSE, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_c2`, x, k, cluster, alpha, restrC, deterC, restr_fact, cshape, niter2, opt, equal_weights, zero_tol)
}

tclust_restr2_eigenv <- function(autovalues, ni_ini, factor_e = 12, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_restr2_eigenv`, autovalues, ni_ini, factor_e, zero_tol)
}

tclust_restr2_deter_old <- function(autovalues, ni_ini, factor_e = 12, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_restr2_deter_old`, autovalues, ni_ini, factor_e, zero_tol)
}

tclust_restr2_deter <- function(autovalues, ni_ini, restr_factor = 12, cshape = 1e10, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_restr2_deter`, autovalues, ni_ini, restr_factor, cshape, zero_tol)
}

tclust_HandleSmallEv <- function(autovalues, zero_tol = 1e-16) {
    .Call(`_tclust_tclust_HandleSmallEv`, autovalues, zero_tol)
}

dmvnrm <- function(x, mean, cov) {
    .Call(`_tclust_dmvnrm`, x, mean, cov)
}

tkmeans_c1 <- function(x, k, alpha = 0.05, niter1 = 3L, zero_tol = 1e-16, points = NULL) {
    .Call(`_tclust_tkmeans_c1`, x, k, alpha, niter1, zero_tol, points)
}

tkmeans_c2 <- function(x, k, cluster, alpha = 0.05, niter2 = 20L, zero_tol = 1e-16) {
    .Call(`_tclust_tkmeans_c2`, x, k, cluster, alpha, niter2, zero_tol)
}

